# Generated by Django 2.1.2 on 2019-07-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20190622_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
