# Generated by Django 2.1.2 on 2019-07-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20190704_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='picture',
            field=models.CharField(default='/pictures/download.jpg', max_length=1000000),
        ),
    ]
