# Generated by Django 2.1.2 on 2019-07-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_auto_20190722_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='author',
            field=models.CharField(default='guest', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='picture',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
