# Generated by Django 2.1.2 on 2019-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20190722_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='picture',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
