# Generated by Django 2.1.2 on 2019-07-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_auto_20190722_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='picture',
            field=models.ImageField(default='pictures/colorful-star', upload_to='pictures/'),
        ),
    ]
