# Generated by Django 2.1.2 on 2019-07-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20190722_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='picture',
            field=models.ImageField(default='pictures/colorful-star.png', upload_to='pictures/'),
        ),
    ]
