# Generated by Django 2.1.2 on 2019-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_auto_20190722_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='picture',
            field=models.ImageField(default='pictures/download.jpg', upload_to='pictures/'),
        ),
    ]
