# Generated by Django 2.1.2 on 2019-07-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_auto_20190722_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='picture',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
