# Generated by Django 2.1.2 on 2019-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Display_Picture',
            field=models.ImageField(default='', upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x03E41950>_pictures'),
        ),
    ]
