# Generated by Django 2.1.2 on 2019-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190709_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Display_Picture',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
